baseURL = 'http://example.org/'
languageCode = 'en-us'
theme="puppet"

copyright = "(c) Mark Phillips 2023"
paginate = 3
defaultContentLanguage = "en"


hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "Tech Docs"
name = "Tech Docs"
url = "/techdocs/"
weight = 10

[params]
author = "Puppet"
description = "A site for technical documentation"
keywords = "blog,developer,personal"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"
